<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ECMAscript6 Promise</title>
</head>
<body>
    <div class="result"></div>
    <div class="chainingResult"></div>

<!--https://poiemaweb.com/es6-promise-->
<script type="text/javascript">
    // 1. 프로미스란?
    //     ES5 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백 함수를 사용한다.
    //     하지만 전통적인 콜백 패턴은 콜백 헬로 인해 가독성이 나쁘고 비동기 처리 중 발생한 에러의 처리가 곤란하며
    //     여러 개의 비동기 처리를 한번에 처리하는 데도 한계가 있다.
    //
    //     ES6에서는 비동기 처리를 위한 또 다른 패턴으로 프로미스(Promise)를 도입했다.
    //     프로미스는 전통적인 콜백 패턴이 가진 단점을 보완하며 비동기 처리 시점을 명확하게 표현할 수 있다는 장점이 있다.
    // 3. 프로미스의 생성
    // 프로미스는 Promise 생성자 함수를 통해 인스턴스화한다.
    // Promise 생성자 함수는 비동기 작업을 수행할 콜백 함수를 인자로 전달받는데 이 콜백 함수는 resolve와 reject 함수를 인자로 전달받는다.

    // 객체 생성
    const promise = new Promise( (resolve, reject) => {
        // 비동기 작업 수행

        // 성공
        // resolve(response);

        // 실패
        // reject('fail');
    } );

    // 4. 프로미스의 후속 처리 메소드
    // Promise로 구현된 비동기 함수는 Promise 객체를 반환하여야 한다.
    // Promise로 구현된 비동기 함수를 호출하는 측(promise consumer)에서는 Promise 객체의 후속 처리 메소드(then, catch)를 통해
    // 비동기 처리 결과 또는 에러 메시지를 전달받아 처리한다. Promise 객체는 상태를 갖는다고 하였다.
    // 이 상태에 따라 후속 처리 메소드를 체이닝 방식으로 호출한다. Promise의 후속 처리 메소드는 아래와 같다.
    // then
    // then 메소드는 두 개의 콜백 함수를 인자로 전달 받는다. 첫 번째 콜백 함수는 성공(fulfilled, resolve 함수가 호출된 상태) 시 호출되고
    // 두 번째 함수는 실패(rejected, reject 함수가 호출된 상태) 시 호출된다. then 메소드는 Promise를 반환한다.
    // catch
    // 예외(비동기 처리에서 발생한 에러와 then 메소드에서 발생한 에러)가 발생하면 호출된다. catch 메소드는 Promise를 반환한다.
    const $result = document.querySelector('.result');
    const render = content => {
        $result.textContent = JSON.stringify(content, null, 2);
    };
    const promiseAjax = (method, url, payload) => {
        return new Promise( (resolve, reject) => {
            const xhr = new XMLHttpRequest();
            xhr.open(method, url);
            xhr.send(JSON.stringify(payload));

            xhr.onreadystatechange = () => {
                if ( xhr.readyState !== XMLHttpRequest.DONE ){
                    return;
                }

                if( xhr.status === 200 ) {
                    resolve(xhr.response);
                } else {
                    reject(new Error(xhr.status));
                }
            };
        } );
    };

    promiseAjax('GET', 'http://jsonplaceholder.typicode.com/posts/1', {})
        .then(JSON.parse)
        .then(
            render, // fulfilled
            console.error // rejected
        );


    // 5. 프로미스의 에러 처리
    // 위 예제의 비동기 함수 get은 Promise 객체를 반환한다. 비동기 처리 결과에 대한 후속 처리는
    // Promise 객체가 제공하는 후속 처리 메서드 then, catch, finally를 사용하여 수행한다.
    // 비동기 처리 시에 발생한 에러는 then 메서드의 두 번째 콜백 함수로 처리할 수 있다.
    promiseAjax('http://errorUrl')
        .then(
            res => console.log(res)
            // , err => console.error(err)
        )
        .catch(err => console.error(err));


    // 6. 프로미스 체이닝
    // 비동기 함수의 처리 결과를 가지고 다른 비동기 함수를 호출해야 하는 경우, 함수의 호출이 중첩(nesting)이 되어 복잡도가 높아지는 콜백 헬이 발생한다.
    // 프로미스는 후속 처리 메소드를 체이닝(chainning)하여 여러 개의 프로미스를 연결하여 사용할 수 있다. 이로써 콜백 헬을 해결한다.
    // Promise 객체를 반환한 비동기 함수는 프로미스 후속 처리 메소드인 then이나 catch 메소드를 사용할 수 있다.
    // 따라서 then 메소드가 Promise 객체를 반환하도록 하면(then 메소드는 기본적으로 Promise를 반환한다.) 여러 개의 프로미스를 연결하여 사용할 수 있다.
    const $chainingResult = document.querySelector('.chainingResult');
    const url = 'http://jsonplaceholder.typicode.com/posts';

    promiseAjax('GET', `${url}/1`)
        .then(res => promiseAjax('GET', `${url}?userId=${JSON.parse(res).userId}`))
        .then(JSON.parse)
        .then(render)
        .catch(console.error);


    // 7. 프로미스의 정적 메소드
    // Promise.resolve
    // 존재하는 값을 Promise로 래핑하기 위해 사용
    // 인자로 전달된 값을 resolve하는 Promise를 생성
    const resolvedPromise = Promise.resolve([1, 2, 3]);
    resolvedPromise.then(console.log); // [ 1, 2, 3 ]

    // Promise.reject
    // 인자로 전달된 값을 reject하는 프로미스를 생성
    const rejectedPromise = Promise.reject(new Error('Error!'));
    rejectedPromise.catch(console.log); // Error: Error!

    // Promise.all
    // 프로미스가 담겨 있는 배열 등의 이터러블을 인자로 전달 받는다.
    // 그리고 전달받은 모든 프로미스를 병렬로 처리하고 그 처리 결과를 resolve하는 새로운 프로미스를 반환
    Promise.all([
        new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
        new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
        new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
    ]).then(console.log) // [ 1, 2, 3 ]
        .catch(console.log);

    // Promise.all 메소드는 전달받은 모든 프로미스를 병렬로 처리한다.
    // 이때 모든 프로미스의 처리가 종료될 때까지 기다린 후 아래와 모든 처리 결과를 resolve 또는 reject한다.
    // 모든 프로미스의 처리가 성공하면 각각의 프로미스가 resolve한 처리 결과를 배열에 담아 resolve하는 새로운 프로미스를 반환한다.
    // 이때 첫번째 프로미스가 가장 나중에 처리되어도 Promise.all 메소드가 반환하는 프로미스는
    // 첫번째 프로미스가 resolve한 처리 결과부터 차례대로 배열에 담아 그 배열을 resolve하는 새로운 프로미스를 반환한다. 즉, 처리 순서가 보장된다.
    // 프로미스의 처리가 하나라도 실패하면 가장 먼저 실패한 프로미스가 reject한 에러를 reject하는 새로운 프로미스를 즉시 반환한다.

    Promise.all([
        new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 1!')), 3000)),
        new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 2!')), 2000)),
        new Promise((resolve, reject) => setTimeout(() => reject(new Error('Error 3!')), 1000))
    ]).then(console.log)
        .catch(console.log); // Error: Error 3!
    // 세번째 프로미스가 가장 먼저 실패하므로 세번째 프로미스가 reject한 에러가 catch 메소드로 전달된다.

    // Promise.race
    // Promise.all 메소드와 동일하게 프로미스가 담겨 있는 배열 등의 이터러블을 인자로 전달 받는다.
    // Promise.all 메소드처럼 모든 프로미스를 병렬 처리하는 것이 아니라 가장 먼저 처리된 프로미스가 resolve한 처리 결과를 resolve하는 새로운 프로미스를 반환한다.
    Promise.race([
        new Promise(resolve => setTimeout(() => resolve(1), 3000)), // 1
        new Promise(resolve => setTimeout(() => resolve(2), 2000)), // 2
        new Promise(resolve => setTimeout(() => resolve(3), 1000))  // 3
    ]).then(console.log) // 3
        .catch(console.log);





</script>

</body>
</html>